# Generated by Django 2.2.10 on 2022-01-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Specify name of the poll', max_length=255, verbose_name='Poll name')),
                ('description', models.TextField(blank=True, help_text='Specify description for the poll', max_length=255, verbose_name='Poll Description')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created / Poll start date')),
                ('date_end', models.DateTimeField(auto_now=True, verbose_name=' Poll end date')),
            ],
            options={
                'verbose_name': 'Poll',
                'verbose_name_plural': 'Polls',
                'ordering': ('id',),
            },
        ),
    ]
