# Generated by Django 3.2.11 on 2022-01-23 16:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 30, 16, 58, 14, 725336, tzinfo=utc), verbose_name='Poll end date'),
        ),
    ]
